add_newline = false
#command_timeout = 750

#format = """
#[┌───────────────────>](bold green)$git_branch
#[│](bold green)$directory$gcloud$kubernetes
#[└─>](bold green) """

format = """
$username$directory$hostname$git_branch$git_commit$git_status$git_state$kubernetes$gcloud$golang$python$terraform$helm
$character"""

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[git_branch]
format = '[git:\(](white)[$branch](bold purple)'

[git_commit]
format = '[\($hash\)](bold green)'

[git_status]
untracked = ''
ahead = '[\[](dimmed red)ahead ${count}[\]](dimmed red)'
diverged = '[\[](dimmed red)ahead ${ahead_count} behind ${behind_count}[\]](dimmed red)'
behind = '[\[](dimmed red)behind ${count}[\]](dimmed red)'
format = '[$all_status$ahead_behind](bold red)[\)](white) '

[gcloud]
format = '[gcp:\(](white)[$project](blue)[\)](white) '

[golang]
format = '[go:\(](white)[$version](bold cyan)[\)](white) '

[helm]
format = '[helm:\(](white)[$version](bold white)[\)](white) '

[hostname]
ssh_only = true
format = '[@:\(](white)[$hostname](red)[\)](white) '

[kubernetes]
format = '[k8s:\(](white)[$symbol$context$symbol]($style)([\(](dimmed $style)[$namespace]($style)[\)](dimmed $style))[\)](white) '
disabled = false

[[kubernetes.contexts]]
context_pattern = "gke_.*_(?P<cluster>dev[\\w-]+)"
style = "cyan"
symbol = ""
context_alias = "gke-$cluster"

[[kubernetes.contexts]]
context_pattern = "gke_.*_(?P<cluster>stg[\\w-]+)"
style = "yellow"
symbol = ""
context_alias = "gke-$cluster"

[[kubernetes.contexts]]
context_pattern = "gke_.*_(?P<cluster>(prd|australia)[\\w-]+)"
style = "red"
symbol = ""
context_alias = "gke-$cluster"

[[kubernetes.contexts]]
context_pattern = "gke_.*_(?P<cluster>[\\w-]+)"
style = "cyan"
symbol = ""
context_alias = "gke-$cluster"

#[kubernetes.context_aliases]
#"dev.local.cluster.k8s" = "dev"
#".*/openshift-cluster/.*" = "openshift"
#"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"

[python]
format = '[py:\(](white)[$version](yellow bold)([\(](dimmed yellow)[$virtualenv](yellow bold)[\)](dimmed yellow))[\)](white) '

[username]
format = '[$user]($style) '
show_always = false

[terraform]
format = '[tf:\(](white)[$workspace](bold 105)[\)](white) '
disabled = true
