#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP2 --mode 1920x1080 --pos 1920x0 --rotate normal --output HDMI1 --off --output VIRTUAL1 --off

bspc monitor DP-1 -d 1 2 3 4 5 
bspc monitor DP-2 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Rofi state=floating follow=on
bspc rule -a Hypnotix.py state=floating follow=on
bspc rule -a Spotify follow=on focus=on

/usr/bin/picom --config ~/.config/picom/picom.conf --experimental-backends &
xsetroot -cursor_name left_ptr &

#$HOME/.config/polybar/launch2.sh

~/.config/polybar/launch.sh --cuts

/usr/bin/nitrogen --restore &
/usr/bin/flameshot &
/usr/bin/nm-applet &
